spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/blps
    driver-class-name: org.postgresql.Driver
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  activemq:
    password: lmao
    user: lmao
server:
  port: 18787
